In [3]:
%run -i "uwb_scikit-learn_RF_pipeline_diff_scen"

Data Pipeline (StandardScaler >> RFClassifier) is created!

Pipeline(memory=None,
         steps=[('standardscaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('randomforestclassifier',
                 RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                        class_weight=None, criterion='gini',
                                        max_depth=None, max_features='auto',
                                        max_leaf_nodes=None, max_samples=None,
                                        min_impurity_decrease=0.0,
                                        min_impurity_split=None,
                                        min_samples_leaf=1, min_samples_split=2,
                                        min_weight_fraction_leaf=0.0,
                                        n_estimators=50, n_jobs=None,
                                        oob_score=False, random_state=None,
                               

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  50 out of  50 | elapsed:    5.2s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  50 out of  50 | elapsed:    0.5s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  50 out of  50 | elapsed:    0.3s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.



Training Time in iter 0: 5.38s

Testing Time in iter 0: 0.62s

Test Accuracy in RF at same scenario in iter 0: 0.9209

Test Accuracy in RF at diff scenario in iter 0: 0.7291

Training in progress! This may take some times ... 



[Parallel(n_jobs=1)]: Done  50 out of  50 | elapsed:    5.1s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  50 out of  50 | elapsed:    0.5s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  50 out of  50 | elapsed:    0.2s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.



Training Time in iter 1: 5.29s

Testing Time in iter 1: 0.56s

Test Accuracy in RF at same scenario in iter 1: 0.9213

Test Accuracy in RF at diff scenario in iter 1: 0.7411

Training in progress! This may take some times ... 



[Parallel(n_jobs=1)]: Done  50 out of  50 | elapsed:    5.4s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  50 out of  50 | elapsed:    0.5s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  50 out of  50 | elapsed:    0.2s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.



Training Time in iter 2: 5.56s

Testing Time in iter 2: 0.56s

Test Accuracy in RF at same scenario in iter 2: 0.9211

Test Accuracy in RF at diff scenario in iter 2: 0.7204

Training in progress! This may take some times ... 



[Parallel(n_jobs=1)]: Done  50 out of  50 | elapsed:    5.5s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  50 out of  50 | elapsed:    0.5s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  50 out of  50 | elapsed:    0.2s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.



Training Time in iter 3: 5.61s

Testing Time in iter 3: 0.56s

Test Accuracy in RF at same scenario in iter 3: 0.9190

Test Accuracy in RF at diff scenario in iter 3: 0.7309

Training in progress! This may take some times ... 



[Parallel(n_jobs=1)]: Done  50 out of  50 | elapsed:    5.3s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  50 out of  50 | elapsed:    0.5s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  50 out of  50 | elapsed:    0.2s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.



Training Time in iter 4: 5.40s

Testing Time in iter 4: 0.58s

Test Accuracy in RF at same scenario in iter 4: 0.9190

Test Accuracy in RF at diff scenario in iter 4: 0.7260

Training in progress! This may take some times ... 



[Parallel(n_jobs=1)]: Done  50 out of  50 | elapsed:    5.1s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  50 out of  50 | elapsed:    0.7s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  50 out of  50 | elapsed:    0.3s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.



Training Time in iter 5: 5.25s

Testing Time in iter 5: 0.77s

Test Accuracy in RF at same scenario in iter 5: 0.9192

Test Accuracy in RF at diff scenario in iter 5: 0.7202

Training in progress! This may take some times ... 



[Parallel(n_jobs=1)]: Done  50 out of  50 | elapsed:    5.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  50 out of  50 | elapsed:    0.4s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  50 out of  50 | elapsed:    0.2s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.



Training Time in iter 6: 5.13s

Testing Time in iter 6: 0.55s

Test Accuracy in RF at same scenario in iter 6: 0.9209

Test Accuracy in RF at diff scenario in iter 6: 0.7251

Training in progress! This may take some times ... 



[Parallel(n_jobs=1)]: Done  50 out of  50 | elapsed:    5.5s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  50 out of  50 | elapsed:    0.5s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  50 out of  50 | elapsed:    0.2s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.



Training Time in iter 7: 5.62s

Testing Time in iter 7: 0.60s

Test Accuracy in RF at same scenario in iter 7: 0.9197

Test Accuracy in RF at diff scenario in iter 7: 0.7279

Training in progress! This may take some times ... 



[Parallel(n_jobs=1)]: Done  50 out of  50 | elapsed:    5.2s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  50 out of  50 | elapsed:    0.5s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  50 out of  50 | elapsed:    0.2s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.



Training Time in iter 8: 5.38s

Testing Time in iter 8: 0.64s

Test Accuracy in RF at same scenario in iter 8: 0.9182

Test Accuracy in RF at diff scenario in iter 8: 0.7333

Training in progress! This may take some times ... 



[Parallel(n_jobs=1)]: Done  50 out of  50 | elapsed:    5.3s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  50 out of  50 | elapsed:    0.6s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  50 out of  50 | elapsed:    0.3s finished



Training Time in iter 9: 5.48s

Testing Time in iter 9: 0.66s

Test Accuracy in RF at same scenario in iter 9: 0.9217

Test Accuracy in RF at diff scenario in iter 9: 0.7294



Training and Testing of 10 iterations finished!

Prediction results save as CSV in file name 'RF_pred_true_10iter.txt'


Total Data Size, Training size, Test Size:
(185790, 3)
(130053, 3)
(55737, 3)

mean accuracy in RF at same scenario: 0.9201 +/- 0.001140

mean accuracy in RF at diff scenario: 0.7283 +/- 0.005823

mean Training Time with std in RF: 5.41 +/- 0.151980 (sec)

mean Testing Time with std in RF: 0.61 +/- 0.064690 (sec)

results save in the file name 'RF_10iter.txt'

[[0.92086047 5.38127089 0.62053442]
 [0.92127312 5.29479146 0.55594039]
 [0.92111165 5.56321168 0.55679226]
 [0.91904839 5.60705638 0.55593228]
 [0.91901251 5.40384746 0.58436942]
 [0.91920986 5.24508858 0.76595449]
 [0.92089635 5.13167739 0.54514313]
 [0.91971222 5.61862588 0.60441184]
 [0.91822308 5.38221526 0.64012384]
 [0.92172166 5